# DataSource Config
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/myblog?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: admin
mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
server:
  port: 9999

shiro-redis:
  enable: true
  redis-manager:
    host: 127.0.0.1:6379

tanjiaming99:
  jwt:
    secret: f4e2e52034348f86b67cde581c0f9eb5
    # token\u6709\u6548\u65F6\u957F\uFF0C\u4E03\u5929\uFF0C\u5355\u4F4D\u662F\u79D2
    expire: 604800
    header: Authorization